/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_goodix_sotest_NativeMath */

#ifndef _Included_com_goodix_sotest_NativeMath
#define _Included_com_goodix_sotest_NativeMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_goodix_sotest_NativeMath
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_goodix_sotest_NativeMath_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_goodix_sotest_NativeMath
 * Method:    unload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_goodix_sotest_NativeMath_unload
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
